version: '3.8'

services:
  http-server:
    build: .
    container_name: video_intercom_http_server
    command: php -S 0.0.0.0:8888
    ports:
      - "8888:8888" # Expose port 8888 for the HTTP server

  websocket-server:
    build: .
    container_name: video_intercom_websocket_server
    command: php ws/bin/ws_server.php
    ports:
      - "8080:8080" # Expose port 8080 for the WebSocket server
