version: '3.8'

services:
  http-server:
    build: .
    container_name: video_intercom_http_server
    command: php -S 0.0.0.0:8888
    ports:
      - "8888:8888" # Expose port 8888 for the HTTP server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.intercom-server.rule=Host(`intercom.orlovdev.ru`)"
      - "traefik.http.routers.intercom-server.entrypoints=websecure"
      - "traefik.http.routers.intercom-server.tls.certresolver=myresolver"
      - "traefik.http.services.intercom-server.loadbalancer.server.port=8888"
    networks:
      - traefiknet

  websocket-server:
    build: .
    container_name: video_intercom_websocket_server
    command: php ws/bin/ws_server.php
    ports:
      - "8080:8080" # Expose port 8080 for the WebSocket server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.websocket-server.rule=Host(`ws.orlovdev.ru`)"
      - "traefik.http.routers.websocket-server.entrypoints=websecure"
      - "traefik.http.routers.websocket-server.tls.certresolver=myresolver"
      - "traefik.http.services.websocket-server.loadbalancer.server.port=8080"
    networks:
      - traefiknet

networks:
  traefiknet:
    external: true
    name: traefiknet
