docker-up:
	docker-compose --env-file ./docker.env up -d

docker-config:
	docker-compose --env-file ./docker.env config

docker-logs:
	docker-compose logs -f

docker-down:
	docker-compose --env-file ./docker.env down
